### PR TITLE
microverse tse approval

### PR DESCRIPTION
**Pull request by firmoholanda**

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes Required :stop:

### First, kudos for your readme 👏 
### Hello @firmoholanda , before getting approval you have fix some issues 
**Original**
image
**Yours**
image

- After `Top stories` -> you should have `More stories` then -> `Culture and travel` then `FEATURED STORIES` then `Opinion ` then `Lastest news`.

**Yours** In mobile view you should have only one column 
image

**Original**
image

**Yours**
image

**Yours**UI is breaking in 738 px,
image

**In index,html**
-  You have use `main` element for your main content because you are using non sementical element `div` there.

>[Optional] Kindly compare your website with original and try to make yours pixel perfect. which is very use for your career.


----
### Don't forgot to request for another code review
----

Pon Muthu Selvam N
_If there is any queries feel free to ping in slack_

**Comment by firmoholanda** [comment]
hi there! all issues fixed. thanks

**Review by mosesogwo — APPROVED** [review]
Good job @firmoholanda , :clap: 

Your project is approved.

**Optional suggestion:** Before merging to master, you may want to take care of this break at 700px. The image should be properly aligned.
Screenshot_2019-11-28_22-55-15.

Good luck in your next project.

**Status: Approved!**

**Comment by firmoholanda** [comment]
done! thanks

**Pull request merged**
